---
title: "Intervallen"
layout: page
permalink: /intervallen
---

# Intervallen

Het interval is een van de belangrijkste bouwstenen van de muziektheorie.
Als we akkoorden willen beschrijven zijn intervallen onmisbaar.
Daarom beginnen we met een korte introductie op intervallen.

Voorkennis:

- Je kent de notennamen

- Je kent kruizen en mollen

> **Definitie**
> 
> Een interval is de afstand tussen twee tonen. 
> Als deze tonen samen klinken spreken we van een *harmonisch* interval. 
> Als deze tonen na elkaar klinken spreken we van een *melodisch* interval.

## Diatoniek

Het belangrijkste interval is het **octaaf**.
Ga je van een toon een octaaf omhoog, dan wordt de frequentie van die eerste toon verdubbeld.
Twee tonen die een octaaf uit elkaar liggen, trillen dus in een verhouding 1:2.
Hoe je dit octaaf verdeelt in kleinere intervallen is een groot probleem waar mensen zich al millennia mee bezig houden.
De oplossingen voor dit probleem verschillen over culturen en tijdperken.
Voor nu zullen we ons beperken tot de oplossing die wordt gebruikt in nagenoeg alle westerse moderne muziek: het **diatonische toonstelsel**.

Het diatonische toonstelsel verdeelt een octaaf in 5 *hele toon* en 2 *halve toon*.
